/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as UsersSearchImport } from './routes/users/_search'
import { Route as UsersSearchIndexImport } from './routes/users/_search/index'

// Create Virtual Routes

const UsersImport = createFileRoute('/users')()

// Create/Update Routes

const UsersRoute = UsersImport.update({
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UsersSearchRoute = UsersSearchImport.update({
  id: '/_search',
  getParentRoute: () => UsersRoute,
} as any)

const UsersSearchIndexRoute = UsersSearchIndexImport.update({
  path: '/',
  getParentRoute: () => UsersSearchRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
    '/users/_search': {
      id: '/users/_search'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersSearchImport
      parentRoute: typeof UsersRoute
    }
    '/users/_search/': {
      id: '/users/_search/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersSearchIndexImport
      parentRoute: typeof UsersSearchImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  UsersRoute: UsersRoute.addChildren({
    UsersSearchRoute: UsersSearchRoute.addChildren({ UsersSearchIndexRoute }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/users"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/users": {
      "filePath": "users",
      "children": [
        "/users/_search"
      ]
    },
    "/users/_search": {
      "filePath": "users/_search.tsx",
      "parent": "/users",
      "children": [
        "/users/_search/"
      ]
    },
    "/users/_search/": {
      "filePath": "users/_search/index.tsx",
      "parent": "/users/_search"
    }
  }
}
ROUTE_MANIFEST_END */
